GET localhost:8080/api/v1/posts
Content-Type: application/json

{
  "page": 1,
  "id": "5cac54df-4e47-4eb0-a5e9-d11df17ce34c"
}

###

POST localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "this is title",
  "text": "this is text",
  "accountId": "5cac54df-4e47-4eb0-a5e9-d11df17ce34c"
}

###

PUT localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": "3da9ca56-2ddf-4bad-b2b7-fbf3b0533dde",
  "title": "this is new title",
  "text": "this is new text"
}

###

DELETE localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": "3da9ca56-2ddf-4bad-b2b7-fbf3b0533dde"
}

###

POST localhost:8080/api/v1/accounts/65884118-feb2-11ec-b939-0242ac120002/description
Content-Type: application/json

{
  "status": "ya dodik",
  "hometown": "kazan",
  "country": "russia",
  "website": "bolshiyeprogi.com",
  "job": "proger"
}

###

PUT localhost:8080/api/v1/accounts/65884118-feb2-11ec-b939-0242ac120002/description
Content-Type: application/json

{
  "status": "ya s marselem v turcii zhdu kalik",
  "hometown": "antaliya",
  "country": "turcija",
  "personalWebsite": "bolshiyeprogi.com",
  "job": "kalyanshick"
}

###

GET localhost:8080/api/v1/accounts/65884118-feb2-11ec-b939-0242ac120002/description