POST localhost/api/v1/questions
Content-Type: application/json

{
  "text": "is it working?",
  "accountId" : "65884118-feb2-11ec-b939-0242ac120002",
  "isAnonymous" : true
}

###

PATCH localhost/api/v1/questions/ba09fdb1-b9ce-46af-9203-a590127ed9f7
Content-Type: application/json

{
  "text": "yeeeees, i'm Ben",
  "accountId" : "65884118-feb2-11ec-b939-0242ac120002"
}

###

GET localhost/api/v1/questions/get-not-answered

###

GET localhost/api/v1/questions/get-answered

###

POST localhost/api/v1/questions
Content-Type: application/json

{
  "text": "second question. yes?",
  "accountId" : "65884118-feb2-11ec-b939-0242ac120002",
  "isAnonymous" : false
}

###

PATCH localhost/api/v1/questions/ba09fdb1-b9ce-46af-9203-a590127ed9f7
Content-Type: application/json

{
  "text": "good job collega",
  "accountId" : "65884118-feb2-11ec-b939-0242ac120002"
}

###

GET localhost/api/v1/questions/ba09fdb1-b9ce-46af-9203-a590127ed9f7